# Generated by Django 4.1.7 on 2023-05-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Values',
            new_name='DataValue',
        ),
    ]
