# Generated by Django 4.1.7 on 2023-05-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dataday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataDay',
        ),
        migrations.AddField(
            model_name='datavalue',
            name='day',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
